# ================================================================================
# DROPIFY TECHNOLOGIES - NEXT.JS APP ROUTER CONFIGURATION
# Professional Web3 Onboarding Platform
# ================================================================================

[build]
  # Simplified Next.js build command for better Netlify compatibility
  command = "npm ci && npm run build"
  
  # Explicit publish directory for Next.js static export
  publish = ".next"
  
  # Build context
  base = ""

[build.environment]
  # Runtime Configuration
  NODE_VERSION = "20.18.0"
  NPM_VERSION = "10.x"
  
  # Next.js Optimizations
  NEXT_TELEMETRY_DISABLED = "1"
  
  # Build Performance
  NPM_FLAGS = "--prefer-offline --no-audit"
  NODE_OPTIONS = "--max-old-space-size=4096"

# ================================================================================
# FRAMEWORK INTEGRATION
# ================================================================================

[[plugins]]
  package = "@netlify/plugin-nextjs"
  
  [plugins.inputs]
    # Explicit configuration for Next.js plugin
    distDir = ".next"
    
    # Static file handling
    includeRobotsTxt = false

# ================================================================================
# ROUTING & REDIRECTS
# ================================================================================

# API Routes Protection
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Professional Demo Routes
[[redirects]]
  from = "/supra"
  to = "/supra-demo"
  status = 301

[[redirects]]
  from = "/acquisition"
  to = "/supra-demo"
  status = 301

# ================================================================================
# SECURITY CONFIGURATION
# ================================================================================

# Global Security Headers (CSP handled by Next.js)
[[headers]]
  for = "/*"
  [headers.values]
    # Content Security - Removed CSP to let Next.js handle it
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Performance Headers
    Cache-Control = "public, max-age=31536000, immutable"

# API Security Headers
[[headers]]
  for = "/api/*"
  [headers.values]
    # CORS Configuration
    Access-Control-Allow-Origin = "https://supra-demo.netlify.app"
    Access-Control-Allow-Methods = "GET,POST,PUT,DELETE,OPTIONS"
    Access-Control-Allow-Headers = "Content-Type,Authorization,X-Requested-With"
    Access-Control-Allow-Credentials = "true"
    
    # API Security
    X-Robots-Tag = "noindex"
    Cache-Control = "no-cache, no-store, must-revalidate"

# Static Asset Optimization
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/favicon.ico"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# ================================================================================
# PERFORMANCE OPTIMIZATION
# ================================================================================

# Edge Functions for Enhanced Performance
[[edge_functions]]
  function = "auth-middleware"
  path = "/auth/*"

# Function Configuration
[functions]
  # Optimized function settings
  node_bundler = "esbuild"
  
  # Regional deployment for lower latency
  included_files = ["lib/**", "contracts/**"]

# ================================================================================
# MONITORING & ANALYTICS
# ================================================================================

[build.processing]
  # Image optimization
  skip_processing = false
  
[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# ================================================================================
# ENVIRONMENT-SPECIFIC CONFIGURATION
# ================================================================================

# Production Context
[context.production.environment]
  NODE_ENV = "production"
  NEXT_PUBLIC_ENV = "production"

# Preview Context  
[context.deploy-preview.environment]
  NODE_ENV = "development"
  NEXT_PUBLIC_ENV = "preview"

# ================================================================================
# END OF CONFIGURATION
# Professional Supra Integration Demo by Dropify Technologies
# ================================================================================
