[package]
name = "dropify"
version = "1.0.0"
authors = ["Dropify Technologies"]

[addresses]
dropify = "_"

[dev-addresses]
dropify = "0x1"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
